# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  #scheme: ''
  sdk: 'iphoneos'
  configuration: ''

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates-Dist-Sil.p12'
    certPwd: $(P12Password)

- task: Xcode@5
  inputs:
    #actions: 'build, clean, test'
    # packageApp: true
    # signingOption: 'default'
    actions: 'build'
    packageApp: false
    scheme: 'CICDDemo'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: '**/CICDDemo.xcodeproj'
#    xcWorkspacePath: '**/*.xcodeproj/CICDDemo.xcworkspace'
    #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
   # xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
   
   # Install Apple certificate
# Install an Apple certificate required to build on a macOS agent machine
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 
    #certPwd: # Optional
    #keychain: 'temp' # Options: default, temp, custom
    #keychainPassword: # Required when keychain == Custom || Keychain == Default
    #customKeychainPath: # Required when keychain == Custom
    #deleteCert: # Optional
    #deleteCustomKeychain: # Optional
    #signingIdentity: # Optional