# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  #scheme: ''
  sdk: 'iphoneos'
  configuration: ''

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates-Dist-Sil.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'CICDRelease.mobileprovision'


- task: Xcode@5
  inputs:
    actions: 'clean build archive'
    sdk: 'iphoneos'
    scheme: 'CICDDemo'
    configuration: 'Release'
    exportOptions: 'plist'
    exportOptionsPlist: '/Users/vsts/agent/2.155.1/work/1/s/CICDDemo/ExportOptions.plist'# path of plist generated in folder for release
    packageApp: true
    provisioningProfileName: 'CICDRelease.mobileprovision'
    signingOption: 'default'
    useXcpretty: false
    xcWorkspacePath: '**/CICDDemo.xcodeproj'
    
    
    
    #useXcpretty: false
    #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
   # xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
   

#RUN TEST CASES
# - task: Xcode@5
#   displayName: 'Running XCTest/XCUITest'
#   inputs:
#     actions: 'test'
#     scheme: 'CICDDemo'
#     sdk: 'iphonesimulator'
#     destinationSimulators: 'iPhone 8'
#     destinationTypeOption: 'simulators'
#     destinationPlatformOption: 'iOS'
#     configuration: 'Debug'
#     signingOption: "auto"
#     xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
#     xcWorkspacePath: '**/CICDDemo.xcodeproj'
#     useXcpretty: true
#     publishJUnitResults: true

#SAVE IPA
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(Build.artifactStagingDirectory)/CICDDemo'

#show ipa in app Artifact folder in azure pipeline
- task: PublishBuildArtifacts@1
  inputs:
   pathToPublish: '$(build.artifactStagingDirectory)/CICDDemo'
   artifactName: 'xcarchive-files'
   artifactType: 'container'

#Distribute in app center
# - task: AppCenterDistribute@3
#   inputs:
#     serverEndpoint: 'App Center Release'
#     appSlug: 'kushal-pathak-prlk/WeatherApp'
#     appFile: '$(build.artifactStagingDirectory)/WeatherApp/**/*.ipa'
#     releaseNotesOption: 'input'
#     releaseNotesInput: 'CI/CD for iOS'
#     destinationType: 'groups'

#publish code coverage

#- task: PublishCodeCoverageResults@1
  # inputs:
    # codeCoverageTool: 'Cobertura'
    # summaryFileLocation: '/Users/vsts/agent/2.155.1/work/1/s/iOS/WeatherApp/coverage-reports/cobertura.xml'
