# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  #scheme: ''
  sdk: 'iphoneos'
  configuration: ''

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates-Dist-Sil.p12'
    certPwd: $(P12Password)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'CICDRelease.mobileprovision'


- task: Xcode@5
  inputs:
    actions: 'clean build archive'
    packageApp: true
    signingOption: 'default'
    #actions: 'build'
    #packageApp: false
    scheme: 'CICDDemo'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/CICDDemo.xcodeproj'
    exportOptions: 'plist'
    exportOptionsPlist: '/Users/vsts/agent/2.155.1/work/1/s/iOS/WeatherApp/ExportOptions.plist'# path of plist generated in folder for release
    #useXcpretty: false
#    xcWorkspacePath: '**/*.xcodeproj/CICDDemo.xcworkspace'
    #exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
   # xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
   
   # Install Apple certificate
# Install an Apple certificate required to build on a macOS agent machine


- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: 'CICDDemo'
    sdk: 'iphonesimulator'
    destinationSimulators: 'iPhone 8'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    configuration: 'Debug'
    signingOption: "auto"
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    xcWorkspacePath: '**/CICDDemo.xcodeproj'
    useXcpretty: true
    publishJUnitResults: true

#SAVE IPA
- task: CopyFiles@2
  inputs:
    contents: '**/*.ipa'
    targetFolder: '$(Build.artifactStagingDirectory)/WeatherApp'
