# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CICDDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CICDDemo
pod 'Moya', '~> 12.0'

    pod 'SwiftKeychainWrapper'
    pod 'FAPanels'
    pod 'MBProgressHUD'
    pod 'ReachabilitySwift'
    pod 'TPKeyboardAvoiding'
    pod 'Charts'

  target 'CICDDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CICDDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
